### ISSUE TITLE
[windows] "operation not supported by the terminal"

### ISSUE THREAD

**Issue by hh9527** [slog-rs/term#8]
OS: Windows 7 64bit

crate 'term' do support windows. I don't known why slog-term complains "not supported".

```rust
fn main() {
    let decorator = slog_term::TermDecorator::new().stderr().build();
    let drain = slog_term::CompactFormat::new(decorator).build().fuse();
    let drain = slog_async::Async::new(drain).build().fuse();
    let log = slog::Logger::root(Arc::new(drain), o!("version" => "0.1"));
    let log = log.to_erased();

    debug!(log, "hi");
}
```

here are the stack:
```text
thread '<unnamed>' panicked at 'slog::Fuse Drain: Error { repr: Custom(Custom { kind: Other, error: StringError("term error: operation not supp
orted by the terminal") }) }', C:\Users\foo\.cargo\registry\src\bar\slog-2.0.0-1.0\src\lib.rs:1317
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: slog::{{impl}}::log::{{closure}}<slog_term::CompactFormat<slog_term::TermDecorator>>
             at ./<panic macros>:8
   1: core::result::Result<(), std::io::error::Error>::unwrap_or_else<(),std::io::error::Error,closure>
             at C:\projects\rust\src\libcore\result.rs:706
   2: slog::{{impl}}::log<slog_term::CompactFormat<slog_term::TermDecorator>>
             at C:\Users\foo\.cargo\registry\src\bar\slog-2.0.0-1.0\src\lib.rs:1315
   3: slog_async::{{impl}}::build::{{closure}}<slog::Fuse<slog_term::CompactFormat<slog_term::TermDecorator>>>
             at C:\Users\foo\.cargo\registry\src\bar\slog-async-2.0.0-1.0\lib.rs:206
   4: std::panic::{{impl}}::call_once<(),closure>
             at C:\projects\rust\src\libstd\panic.rs:296
   5: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
             at C:\projects\rust\src\libstd\panicking.rs:454
   6: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
   7: std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
             at C:\projects\rust\src\libstd\panicking.rs:433
   8: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
             at C:\projects\rust\src\libstd\panic.rs:361
   9: std::thread::{{impl}}::spawn::{{closure}}<closure,()>
             at C:\projects\rust\src\libstd\thread\mod.rs:360
  10: alloc::boxed::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\liballoc\boxed.rs:638
  11: std::sys::imp::thread::{{impl}}::new::thread_start
             at C:\projects\rust\src\libstd\sys\windows\thread.rs:50
```

**Comment by dpc** [comment]
Could you help me obtain a backtrace from the worker-thread? Eg. by running without using `slog_async` (and wrapping the `CompactFormat` in a `Mutex` instead to make it `Sync`). I'd be guessing that's one of the operations on the terminal itself that is failing: https://github.com/slog-rs/term/blob/master/src/lib.rs#L1072 .  I don't have Windows machine to debug this.

**Comment by hh9527** [comment]
I have got the exception point: https://github.com/slog-rs/term/blob/master/src/lib.rs#L1096

Windows does not support `attr` other than bg/fg, so it seemed we should ignore that error, or use an alter impl for `start_key`.
